version: "3.8"

services:
  todo:
    image: godack/todo-family:latest
    container_name: todo-app
    ports:
      - "3000:3000"
    volumes:
      - ./db.sqlite:/app/db.sqlite
    restart: unless-stopped
